
# NOTE: This file could be used for testing the API with Visual Studio Code


####  POSTS APIs  ####

## Retrieve all the posts
GET http://localhost:3001/api/posts HTTP/1.1
###

## Create a new post (auth required)
POST http://localhost:3001/api/posts HTTP/1.1
Content-Type: application/json

{
  "title": "This is an amazing post!",
  "text": "This is an example of post for testing APIs",
  "maxComments": 5
}
###

## Delete a post (auth + owner or admin)
DELETE http://localhost:3001/api/posts/9 HTTP/1.1
###


####  COMMENTS APIs  ####

## Retrieve comments for a specific post
GET http://localhost:3001/api/posts/3/comments HTTP/1.1
###

## Retrieve a single comment by ID
GET http://localhost:3001/api/comments/4 HTTP/1.1
###

## Add a comment to a post (auth optional: anonymous allowed)
POST http://localhost:3001/api/posts/3/comments HTTP/1.1
Content-Type: application/json

{
  "text": "A simple comment for testing APIs"
}
###

## Edit a comment (auth + owner or admin)
PUT http://localhost:3001/api/comments/5 HTTP/1.1
Content-Type: application/json

{
  "text": "Edited comment for testing APIs"
}
###

## Delete a comment (auth + owner or admin)
DELETE http://localhost:3001/api/comments/5 HTTP/1.1
###


####  "INTERESTING" APIs  ####

## Mark a comment as interesting (auth required)
PUT http://localhost:3001/api/comments/4/interesting HTTP/1.1
Content-type: application/json

{
  "id" : 3,     // post ID
}
###

## Unmark a comment as interesting (auth required)
PUT http://localhost:3001/api/comments/4/not-interesting HTTP/1.1
Content-type: application/json

{
  "id" : 3,     // post ID
}
###